### ISSUE TITLE
nice! need get popup info from each itm

### ISSUE THREAD

**Issue by vlasvlasvlas** [skeate/Leaflet.timeline#1]
Hi this is really a great plugin,

i was wondering how can i add a simple popup info from each element (Earthquakes demo for example), on click over each eartquake on map to display a simple popup with the info related to each earthquake?

thanks!!

**Comment by skeate** [comment]
Thanks!

In the example, the metadata from the USGS feed is still there, as `properties` [(see the spec)](http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php). For example, if you want the popup to be a link to more information, you could do:

```javascript
var timeline = L.timeline(data, {
  formatDate: function(date){
    return moment(date).format("YYYY-MM-DD HH:MM:SS");
  },
  pointToLayer: function(data, latlng){
    var hue_min = 120;
    var hue_max = 0;
    var hue = data.properties.mag / 10 * (hue_max - hue_min) + hue_min;
    return L.circleMarker(latlng, {
      radius: data.properties.mag * 3,
      color: "hsl("+hue+", 100%, 50%)",
      fillColor: "hsl("+hue+", 100%, 50%)"
    //vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    }).bindPopup('<a href="'+data.properties.url+'">click for more info</a>');
    //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  }
});
```

**Comment by vlasvlasvlas** [comment]
thanks a lot!
