### ISSUE TITLE
SASS syntax?

### ISSUE THREAD

**Issue by MtnBiker** [skeate/Leaflet.timeline#100]
I'm using SCSS (not taking sides)

I ran `sass-convert leaflet.timeline.sass leaflet.timeline.scss` and got complaints about the `;` in the SASS. I'd change it except I can't really keep my own git straight and I don't pretend to know the correct syntax. The converter worked after removing all semi-colons. Thanks for listening

**Comment by skeate** [comment]
I think this was due to some loose handling of the syntax in older Sass versions. Have decided using sass wasn't worth the overhead, so I just converted it to CSS.
