### ISSUE TITLE
Links to webpage broken

### ISSUE THREAD

**Issue by jebyrnes** [skeate/Leaflet.timeline#13]
Can't see the demos without the pages! The links in the Readme file appear broken.

**Comment by skeate** [comment]
Weird, both http://skeate.github.io/Leaflet.timeline and http://skeate.github.io/Leaflet.buffer are down. Investigating

**Comment by skeate** [comment]
Regenerated the gh-pages files and they seem to be up now. Weird.

Thanks for the heads up!
