### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ondavermel** [skeate/Leaflet.timeline#133]
![Screen Shot 2019-10-20 at 2 38 47 PM](https://user-images.githubusercontent.com/47543288/67164317-6a1ca300-f347-11e9-8a80-b324ec35b6b0.png)

**Comment by L0per** [comment]
Getting the same thing with my map once I reached a certain number of timepoints.

**Comment by skeate** [comment]
@L0per can you set up an example of this happening? Would help in debugging it.

**Comment by L0per** [comment]
@skeate I'm currently using it on a covid-19 tracking site I made as a project: http://covid2019tracker.appspot.com/

The map tracks the total number of cases. The github is https://github.com/L0per/wuhan-coronavirus. 

Using chrome, you can see the map stops at 3/9, which is when I first started getting the error, but it works fine in firefox.

The javascript for the map is in `static/js/mas.js`.

Sorry if that's what you meant by setting up an example, I'm pretty new to coding and github. Thanks!

**Comment by skeate** [comment]
That's very helpful, thank you!

**Comment by skeate** [comment]
This is fixed in 1.4.1. Not only is it now using iterative versions of the algorithms (so call stack size is no longer an issue), it's also using a self-balancing tree so you should see significant performance improvement.

@L0per do you mind if I link to that site in the readme, as an example of the plugin "in the wild"?

**Comment by L0per** [comment]
Maybe not yet, it appears to have broken with the more recent database
updates, so I'll have to fix it first within the next few weeks.
