### ISSUE TITLE
Issue with Playback-Function on point-Timeline

### ISSUE THREAD

**Issue by clemens-boisseree** [skeate/Leaflet.timeline#138]
Hi, I hope, I can still get some support for this great plugin.
I'd like to get a point-timeline with about 4000 points in a timerange of one year. I have the data in a json-file, with an start and end-date being the same. Exempel:
`{ "start": "2019-01-01", "end": "2019-01-01"}`

That leads to the problem of the playback-function doesn't work on play while while dragging the slider or just using the back- and forward-buttons work like a charme. 

My function looks like this:
```
var pointTimeline = L.timeline(rechts, {
    onEachFeature: onEachFeature,
    style: function (feature) {
        return {
            radius: 5,
            color: 'red',
            fillColor: 'white'
        }},
        pointToLayer: function (feature, latlng) {
            return L.circleMarker(latlng, pointTimeline);
        }
});


var slider = L.timelineSliderControl({
    formatOutput: function (date) {
        return moment(date).format("DD-MM-YYYY");
    },
    enableKeyboardControls: true,
    steps: 3632
});
map.addControl(slider);
pointTimeline.addTo(map)
slider.addTimelines(pointTimeline);
```

Any idea of what I could do to get the playback-function work?

**Comment by skeate** [comment]
It's been a while since I've worked on this (sorry everyone; updates are hopefully coming soon) but I'm pretty sure you need some non-zero amount of time for the event to appear during playback. Next and previous work because they can pick up specific data points, even if their times are identical. I'm a little surprised that manually dragging the slider works, but it's probably the same idea as next/prev.

Could you add times to the data, or add a day to the end timestamp?

**Comment by clemens-boisseree** [comment]
Hi Jonathan, thanks for getting back that quickly.

Adding a full day would distort the visualisation. I want to show a timeline of attacks and where they took place, so the attack-point for Day X should not show up on Day+1.
Adding hours and minutes could help, but adding both led to a "Invalid date"-Error. I used the follow format for the try 
`2019-01-03 23-59`
Do you have any idea for a working format?

I'll add my case th #137 .

**Comment by skeate** [comment]
The dates get parsed by getting run through `new Date()`, so it has to be something that understands. `2019-01-03 23:59` works for me, but as best I can tell from the [spec](https://tc39.es/ecma262/#sec-date-time-string-format) that's nonstandard. `2019-01-03T23:59` is better.
