### ISSUE TITLE
Slider and Timeline-Points dont show up mobile on iOS

### ISSUE THREAD

**Issue by clemens-boisseree** [skeate/Leaflet.timeline#139]
Another issue I noticed after being almost done with my map:

Slider and Timeline-Points don't show up on any iOS-Device while there are no problems at all with Android or Desktop.

I load the data with gejson and ajax

```
function loadJSON(file, callback) {
    var xobj = new XMLHttpRequest();
    xobj.overrideMimeType("application/json");
    xobj.open('GET', file, false);
    xobj.onreadystatechange = function () {
        if (xobj.readyState == 4 && xobj.status == "200") {
            callback(xobj.responseText);
        }
    };
    xobj.send(null);
}
loadJSON("data/rechts2019.json", function (response) {
    rechts = JSON.parse(response)
});

```
and then add slider and points with timeline.js

```
var pointTimeline = L.timeline(rechts, {
    onEachFeature: onEachFeature,
    style: function (feature) {
        return {
            radius: 5,
            color: 'red',
            fillColor: '#fff'
        }
    },
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, pointTimeline);
    }
});


var slider = L.timelineSliderControl({
    formatOutput: function (date) {
        return moment(date).format("DD-MM-YYYY");
    },
    enableKeyboardControls: true,
    steps: 7000
});
map.addControl(slider);
pointTimeline.addTo(map)
slider.addTimelines(pointTimeline);
```
you can find the status quo of my visualization here:
http://test.clemens-boisseree.de/crimemap-2019/

Any ideas for my problem?

**Comment by skeate** [comment]
I don't have any iOS devices to test, so I need more info. Are you talking about the little tick marks? i.e.
![image](https://user-images.githubusercontent.com/387382/75277689-796c9b00-57d6-11ea-83fc-8962f111f10d.png)


 If so, that's not something I can fix. [The browser just doesn't support them](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#Browser_compatibility).

**Comment by clemens-boisseree** [comment]
No, the slider itself does not show up, neither does the point-layer.

![Bild von iOS](https://user-images.githubusercontent.com/26927720/75277949-47c0f780-5809-11ea-8db9-14032c8edf98.jpg)

**Comment by clemens-boisseree** [comment]
Just an quick update on that:
The Problem was with moment.js and its compatibility with ios. A change to dayjs solved that problem for me.
