### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nickurban** [skeate/Leaflet.timeline#14]
Hi, are you releasing this project as open source? 

If you're not particular, I recommend adding the MIT license, which is available here: http://opensource.org/licenses/MIT

The standard place for your license is LICENSE.txt (or LICENSE.md) in your project root. 

Thanks!

Nick

**Comment by skeate** [comment]
I did note the license in the package.json but I always forget the actual license file :|

It's been added.

**Comment by nickurban** [comment]
Thanks!
