### ISSUE TITLE
Getting the current timestamp

### ISSUE THREAD

**Issue by lymine1996** [skeate/Leaflet.timeline#150]
Hi, I'm wondering if there is a way that I can get the current timestamp of the slider bar? And How should I update the color of each feature (polygon) at different time points?

**Comment by timelyportfolio** [comment]
This code https://github.com/timelyportfolio/leaftime/issues/1#issuecomment-635742475 combines R+JS but the JS sort of accomplishes what I think you are trying to achieve.  In this case, the user wanted to change a different polygon layer based on time.  Happy to help adapt to your use case.  `layerManager` is not available on base leaflet JS, so we'll need to identify/find the appropriate layer differently.

```
function(el,x) {
  var colors = %s;
  var map = this;
  // get the timeline control
  var timeline = map.layerManager._byCategory.timeline.getLayers()[1];
  
  // use R leaflet layerManager to get franconia polygon layer group
  var franconia = this.layerManager.getLayerGroup('franconia')
  
  timeline.on('change', function() {
    // figure out what time is current selected on timeline and select that color
    var time_selected = this.time;
    var idx = this.times.indexOf(time_selected);
    // but when playing instead of stepping times will not match exactly so in this case we will
    //   crudely bisect the array in a very inefficient way; easy to optimize if there is a need
    if(idx === -1) {
      this.times.forEach(function(d,i) {
        d <= time_selected ? idx = i : idx = idx;
      })
    }
    var color = colors[idx];
    franconia.setStyle({fillColor: color});
    // could also send to Shiny here if helpful
  })
}
```

**Comment by lymine1996** [comment]
Thank you so much! 
This setStyle() function did help me to solve my problem. I couldn't find it in the documentation but it works when I try to apply different colors to the same features according to a set of time-series values. I'll put down my code here so that people having the same issue might be able to use it as a reference.

`<script>
	function getColorFor(d) {
	return d > 10000 ? '#800026' :
	d > 5000 ? '#BD0026' :
	d > 1000 ? '#E31A1C' :
	d > 500 ? '#FC4E2A' :
	d > 100 ? '#FD8D3C' :
	d > 50 ? '#FEB24C' :
	d > 10 ? '#FED976' :
	'#FFEDA0';
	}
	  
      var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
      var osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors';
      var osm = L.tileLayer(osmUrl, {maxZoom: 18, attribution: osmAttrib});
      var map = L.map('map', {layers: [osm], center: new L.LatLng(37,-96), zoom: 4 });
      var timeline;
      var timelineControl;
	  var index = 0;
	  const DayInMilSec = 60*60*24*1000;
	  
	  function splitStr(str,num) {
		var newStr = str.split(",")
		return parseInt(newStr[num])
	  }
	  
	  var styleFunc = function(_data){
            return {
              stroke: false,
              color: getColorFor(splitStr(_data.properties.cases_ts, index)),
              fillOpacity: 0.5
            }
          }

      function onLoadData(data){
		console.log(data);
        timeline = L.timeline(data, {
          style: styleFunc,
          waitToUpdateMap: true,
          onEachFeature: function(feature, layer) {
            layer.bindTooltip(feature.properties.today_case);
          }
        });

        timelineControl = L.timelineSliderControl({
          formatOutput: function(date) {
            return new Date(date).toLocaleDateString();
          },
          enableKeyboardControls: true,
		  steps: 100,
        });
        timeline.addTo(map);
        timelineControl.addTo(map);
        timelineControl.addTimelines(timeline);
		timeline.on('change', function(){
		  index = Math.floor((this.time-this.start)/DayInMilSec);
		  this.setStyle(styleFunc);		 
        });
      }
    </script>`

**Comment by skeate** [comment]
`setStyle` is coming from the Leaflet GeoJSON layer class. https://leafletjs.com/reference-1.6.0.html#geojson-setstyle

The Timeline layer is a subclass of that, so it inherits all its properties and methods.

As for the `this.time` docs .. That does appear to be missing, and the generated docs on the site aren't working; I'll fix that. Thanks for bringing it to my attention
