### ISSUE TITLE
How to load plain geojson

### ISSUE THREAD

**Issue by barney2074** [skeate/Leaflet.timeline#154]
Hello,

Sorry if this is an obvious question- but how can I load a normal geojson file ??
i.e the 'borders' sample has the `onLoadData()` function in the json file, and there is a javascript (border-parse.js) to parse the original geojson

I can generate a geojson file that has all of the data in the correct format & I'd like to avoid another step in processing it
thanks in advance

Andrew

**Comment by skeate** [comment]
Use your favorite data loader (`fetch`, `$.get`, whatever) and then `L.timeline(data)`. The border example's border-parse.js is also a preprocessing step; it's not run every time the data is fetched. Part of the preprocessing is to make it into a `jsonp` file, where it's all the data passed into a function call. The function it calls is `onLoadData`, defined here: https://github.com/skeate/Leaflet.timeline/blob/master/docs/examples/borders.html#L59-L72

Note: JSONP is *not* recommended today; I just haven't updated the example

**Comment by barney2074** [comment]
o.k thanks Jonathan

I'll give it a try.
I'm new at this, so really feeling around in the dark- an updated example would be great if you get a chance


Andrew
