### ISSUE TITLE
Error and breaks Rails ActionText

### ISSUE THREAD

**Issue by MtnBiker** [skeate/Leaflet.timeline#155]
I ` yarn upgrade` to get a Bootstrap icon upgrade, but it broke something with Leaflet.timeline. Now getting this error on page load. See below where I think the problem is with the leaflet.timeline version.

    index.js:7 Uncaught Error: Cannot find module './Timeline.ts'
    at webpackMissingModule (index.js:7)
    at Object../node_modules/leaflet.timeline/dist/index.js (index.js:7)
    at __webpack_require__ (bootstrap:19)
    at Module.<anonymous> (bootstrap:83)
    at Module../app/javascript/packs/application.js (application.js:99)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    
And this causes Rails ActionText to not work correctly for some reason.

    Ruby ruby 2.6.6-p146
    Rails 6.0.3.3 [Problem started with 6.0.0, but upgraded hoping would fix problem]

Update 1: **tried running here [https://npm.runkit.com/leaflet.timeline](https://npm.runkit.com/leaflet.timeline)** and got this error `Error: Cannot find module './Timeline.ts'` so not just a probem with my app.

Update 2: `yarn add leaflet.timeline@1.3.0` fixed it. So rolling back from 1.4.3 fixed it. I tried 1.0.0, but had other problems, so tried 1.3.0 because it was pre TypeScript and the error appears to relate to .ts file. Haven't tried the versions between 1.3.0 and 1.4.3, but will if that will help debug.

My app now works, but this is still an issue.

**Comment by gezonthenet** [comment]
I too am having this issue. Is there a fix apart from rolling back to 1.3.0?

**Comment by skeate** [comment]
This was due to a major fail in bundling things properly. 1.6.0 should fix this
