### ISSUE TITLE
Issue with ticks not being refreshed

### ISSUE THREAD

**Issue by jusefb** [skeate/Leaflet.timeline#16]
Hi,

I think I have found an issue with the refresh of the timeline ticks. I am building an interactive map that allows to load different sets of data for the timeline. However only the first time the Timeline is rendered the ticks display correctly. Subsequently even creating completely new instances of the timeline does not reset the ticks but adds them on top of one another. I have pinpointed the issue to the fact that the "times" property of the Timeline was not reset upon initialisation of the timeline. Unfortunately I am not familiar with cofeescript so can not submit a pull request. here is what I have changed in the JS file to make it work.

```javascript
initialize: function(timedGeoJSON, options) {
      this.times = [];
     ...
    },
```

Hope this will help in fixing the bug.

Kind regards

Jusef

**Comment by skeate** [comment]
Thanks!

Eventually if I find myself with some spare time to work on this more, I'll convert it to ES6.

**Comment by jusefb** [comment]
That would be awesome. Thanks for the fix
