### ISSUE TITLE
Drag not working on mobile

### ISSUE THREAD

**Issue by raidenfreeman** [skeate/Leaflet.timeline#17]
On mobile chrome, android and ios, dragging the slider is not working. Touching on the bar will set the slider correctly though. Also, thank you very much for the plugin.

**Comment by easherma** [comment]
I noticed this as well, the timeline control is not very mobile friendly.

**Comment by tconroy** [comment]
+1 .. any ideas how to fix this? Would love to use this plugin on a mobile-focused project but not entirely sure if it's capable.
