### ISSUE TITLE
Next / Previous buttons strange behaviour

### ISSUE THREAD

**Issue by markstuart** [skeate/Leaflet.timeline#18]
Hi @skeate, thanks for making a great plugin :)

I was looking at your demos and I noticed something odd with the way the next/prev buttons work in the [country borders](http://skeate.github.io/Leaflet.timeline/borders.html) demo. I click on the `next` button and it takes me a long way across the timeline and then starts to just cycle back and forth between two points around that time. If I try to use the `prev` button it jumps back and then gets stuck in another loop on successive clicks. Is this just an issue with the data for that map? The other demo works as expected.

Another thing I see with the use of the next/prev buttons is that using them doesn't update the date/time display on the far right of the slider. Is this expected to work? Or would you like a PR for a new feature?

**Comment by markstuart** [comment]
Ah... I think I've answered my first question. The country borders demo appears to be using `L.TimelineVersion = '0.3.0'` and the changelog states that in v0.4.0 you
> Fixed a bug where next/previous buttons wouldn't work as expected if input wasn't sorted (.. by sorting the input)

**Comment by markstuart** [comment]
I pulled down the repo and had a look around, and running `examples/borders.html` locally shows that the date/time display does get updated with the latest version of the codebase.

So I guess the main takeaway is that I could research a bit more before raising issues (:stuck_out_tongue_winking_eye:) and the demo code is out of date.

I'll try to get some time to raise a PR for updating the demos on the `gh_pages` branch.

**Comment by skeate** [comment]
Yeah, I keep forgetting about poor `gh-pages`. I'll update the examples to the latest.

**Comment by skeate** [comment]
Fixed with 0c1e544e3156a3ee5f60ea3164119f1fe0209040

**Comment by markstuart** [comment]
Thanks for your speedy response on this!
