### ISSUE TITLE
New npm package with latest code

### ISSUE THREAD

**Issue by hansthen** [skeate/Leaflet.timeline#186]
Would it be possible to make a new npm package with the latest code? I would like to use the version that has parameters for "startExclusive" and "endExclusive".

**Comment by skeate** [comment]
oof, coming back to this code after years of neglect is rough.

I just published 1.6.0 which should have it

**Comment by hansthen** [comment]
You are the man!

Op do 8 feb 2024 om 03:58 schreef Jonathan Skeate ***@***.***
