### ISSUE TITLE
Getting the correct date

### ISSUE THREAD

**Issue by vlasvlasvlas** [skeate/Leaflet.timeline#2]
Hi, the thing is working great,

thou i got a strange issue:

im getting date for each point from a postgresql table like this:

extract(epoch from ven.fecha at time zone 'utc')

for example:
sql:
select to_timestamp(1230955200) ;
result:
2009-01-03 02:00:00-02

So great, i'm using that timestamp, but it gets really all confused:

http://i.imgur.com/73yxR97.png

so i noticed that earthquake example got a similiar date timestamp but with 13 characters, not 10.

so i just added 3 zeros at the end, and everything works great now

i'm still wondering whats the correct way to extract date columns to use with this plugin

correct timestamp: 1230955200 + three zeros = 1230955200000
that got my date label at timebar OK.

**Comment by skeate** [comment]
Adding three zeros is, essentially, correct. Really, multiplying by 1000: in Postgres (and many other places), timestamps are in seconds, but in Javascript, timestamps are in milliseconds.

**Comment by vlasvlasvlas** [comment]
great thanks! :)
