### ISSUE TITLE
map.removeLayer( ..timeline.. ) generates error

### ISSUE THREAD

**Issue by DrYSG** [skeate/Leaflet.timeline#24]
When I add the timeline layer to the L.LayerControl and then try to uncheck/check the layer to hide. I get an error. This also happens in another place in my code where I want to destroy the layer and load a new layer.

I really need to be able to load/unload the L.timeliner, since users will be trying out different GeoJSON data in sequence, and need to refresh the layer (as well as hide it).

``` javascript
             if (typeof timeLayer != 'undefined') {
                 console.log('remove the timeline layer');
                 layerControl.removeLayer(timeLayer);
                 theMap.removeLayer(timeLayer);
             }
```

At first I was really surprised at the chrome debugger which was showing me the error occurred in coffeescript. [I only copied the /dist folder to my project]. But now I see that timeline.js has the coffeescript at the bottom. Unfortunately, I do not speak coffeescript so I do not know what is the problem.

```
Uncaught TypeError: this.timeSliderControl.removeFrom is not a function
L.Timeline.L.GeoJSON.extend.onRemove @ leaflet.timeline.coffee:185
L.Map.include.removeLayer @ leaflet-src.js:2569
L.Control.Layers.L.Control.extend._onInputClick @ leaflet-src.js:9110
```

The error is coming from the statement **"@timeSliderControl.removeFrom map"**

``` coffeescript
  onRemove: (map) ->
    L.GeoJSON.prototype.onRemove.call this, map
    @timeSliderControl.removeFrom map

  getDisplayed: -> @ranges.lookup @time

```

**Comment by skeate** [comment]
Sorry for the slow reply. Not sure why this is failing; it's basically saying [this method](http://leafletjs.com/reference.html#control-removefrom) doesn't exist (or, at least, is not a function. which is even stranger?)

I have a feeling this will just go away once I'm done with the refactor, which has been moving along at a surprising clip. No promises, but it should be done within the week.


The unminified dist files do have the Coffeescript in the embedded sourcemap at the bottom of the file. If you want to check out the code without the sourcemapping, you can either disable Javascript source maps in your browser or get rid of the `//# sourceMappingURL` line in the code.

**Comment by DrYSG** [comment]
I can certainly wait for the refactor. That will be great. And yes, I figured out about the sourceMapping, but you can imagine my initial surprise.
