### ISSUE TITLE
Timeline features not removed on change with multiple timeline layers

### ISSUE THREAD

**Issue by rpavery** [skeate/Leaflet.timeline#29]
I'm using the new `1.0.0-beta` framework which allows multiple timeline layers to be controlled by a single `TimeSliderControl`. When a single timeline layer is controlled by the slider, everything works as expected. However, when two layers are added to the `TimeSliderControl`, it looks like features are not removed correctly on the map. Initial inspection shows that in the multiple timeline case, `timeline.getDisplayed()` returns an empty array when there are certainly items on the map. This prevents them from being removed in the `Timeline.updateDisplayedLayers()` method.

**Comment by rpavery** [comment]
I have a [demo site](http://ryanavery.net/cc/test.html) up for testing right now where you can see that as you move the slider, the lines get darker than they should and moving it back to the beginning does not remove all the features.

**Comment by rpavery** [comment]
I looked into this a little bit more and on my demo, somehow when moving the slider, projects from the `completedProjects` timeline get pushed into the `projects` timeline. Not sure how this is happening, but it might help with troubleshooting too. I'm curious if I'm adding the timelines to the `TimeSliderControl` correctly.

**Comment by skeate** [comment]
Once I get a chance, I'm going to go ahead and download your files and try it locally, but in the meantime I've uploaded a non-minified, sourcemapped version of the JS file into the `dist/` folder here, to help with debugging

**Comment by pfoser** [comment]
Same here - works as expected with one layer, but when adding a second one the features are not removed on change.

**Comment by Pililo** [comment]
Any updates on this? Having the same problem when working with more than one timeline, they start overlapping and aren´t removed. Any help on this or a workaround? Great plug-in btw!

**Comment by gonesurfing** [comment]
Same issue here. Kind of a show stopper with more than one layer. I haven't figured out a way around it.

**Comment by gonesurfing** [comment]
Changing line 277 from "this.removeLayer(toRemove[0].layer, false)" to "this.removeLayer(toRemove[0].layer, true)" seems to fix the issue. I'm too tired to comprehend quite why it works right now.

**Comment by ebrelsford** [comment]
Changing [this line](https://github.com/skeate/Leaflet.timeline/blob/master/src/Timeline.js#L186) nearly works for me, but the first feature seems to be stuck, presumably because of the issue @rpavery mentions above.

@skeate what is the use of having `displayedLayers`?

**Comment by ebrelsford** [comment]
I created [a fork that fixes this](https://github.com/ebrelsford/Leaflet.timeline/tree/remove-displayed-layers) if you're interested in taking a look. It gets rid of `displayedLayers`.

**Comment by skeate** [comment]
Merged the PR, so this should be closeable.

**Comment by ebrelsford** [comment]
Looks good to me, thanks for merging that @skeate!

**Comment by easherma** [comment]
I still seem to having this problem, and am confused from this thread what the fix is?

**Comment by ebrelsford** [comment]
@easherma there hasn't been a release since this was merged in, are you using master?

I can't remember precisely what the issue was that kept the features from updating but it had to do with `displayedLayers`. You can see [the PR for details](https://github.com/skeate/Leaflet.timeline/pull/35/files).

**Comment by easherma** [comment]
I am using master. I looked at your changes to the code and it seems to line up with what I'm using. However, the actual bug itself seems to remain; I've tried adding only one or the other between my two layers. Both work by themselves, but don't get removed if I've got more than one layer added to the timeline control.

**Comment by ebrelsford** [comment]
Post an example somewhere? My PR added [this example showing multiple timeline layers working](https://github.com/skeate/Leaflet.timeline/blob/master/examples/multipletimelines.html), maybe you could compare yours to it.

**Comment by easherma** [comment]
I did see that example, and spent some time comparing my code to it and no dice. I'll post an example ASAP, I need to go through and refactor and clean up the code (which, for all we know, could end up solving the problem), or plug my data into your example and see if it works.
