### ISSUE TITLE
setTime does not update slider knob position

### ISSUE THREAD

**Issue by dnass** [skeate/Leaflet.timeline#31]
Calling `setTime` on `timelineSliderControl` does not cause the position of the slider knob to update. Clicking prev/next will cause the knob to move correctly to the ticks before/after the updated time; however, the play button will play it from the original start time, not from the updated time.

Also, it seems that the `setTime` method needs to be called on both `timelineSliderControl` and `timeline` in order to update both. Perhaps setting the time of the control should automatically update the timeline, since one typically wouldn't want the timeline and slider to be out of sync.

**Comment by g3org1** [comment]
I have the same problem, setTime works well and displays the data of the corresponding date, but it is not reflected in the timeline, which is a problem for me.

**Comment by g3org1** [comment]
I managed to solve it by modifying the plugging code by adding this line in setTime          

setTime: function(t) {
            $('.time-slider').prop("value",t);//this line
            this._sliderChanged({
              type: "change",
              target: {
                value: t
              }
            })
          },


the problem is that it would damage the program if you have more than two lines of time (I think), but for me it's enough
