### ISSUE TITLE
Webpack won't build the required JS and CSS files

### ISSUE THREAD

**Issue by IsaacHub** [skeate/Leaflet.timeline#49]
In earthquakes.html file, the following files are linked:
```
<script src="leaflet-src.js"></script>
<script src="leaflet.timeline.min.js"></script>
<link href="leaflet.css" rel="stylesheet">
```

While I opened up in the browser, it's **404 Not found**.

In terminal, the webpack build was successful, but no files are copied to **examples/** directory. Could someone help me what am I missing?

![phpstorm64_2017-03-22_17-59-57](https://cloud.githubusercontent.com/assets/20126441/24197881/79a6364c-0f29-11e7-863e-0408be81fe05.png)

**Comment by skeate** [comment]
If you run `npm start`, it'll run the webpack-dev-server. Then http://localhost:8112/examples/ should work.

I suppose I should add a note to that effect in the readme 😅

**Comment by skeate** [comment]
Apparently there are still a couple issues with that (earthquakes.html is looking for leaflet.timeline.min.js, and I change the build to get rid of the .min)

**Comment by skeate** [comment]
I've updated the examples to have the right filename and added a line in the README about how to run them. Feel free to reopen if you run into any problems.
