### ISSUE TITLE
Playback only plays backwards

### ISSUE THREAD

**Issue by PennyBeames** [skeate/Leaflet.timeline#6]
Hi!

I've seriously been waiting for something like this for ages. Thank you for putting the work into it.

One thing, though. I seem to have gotten the timeline to work, at least the draggable part, but the play button will only go backwards. If I press play as soon as the page loads, nothing happens. If I drag the circle to anywhere along the timeline and then press play, the timeline and dots play perfectly, but in reverse.

Any ideas?

Link: http://pennybeames.net/maps/PermitsTOTime.html

Code:

          var timeline = L.timeline(permits, {
			  formatDate: function(date){
				return moment(date).format("YYYY-MM-DD");
			  },
			    pointToLayer: function (feature, latlng) {
		  		return L.circleMarker(latlng, permitsStyle(feature));},
		  		onEachFeature: onEachFeature
			});
			timeline.addTo(map);

**Comment by skeate** [comment]
That's strange. Seems like it's some kind of overflow issue?

Your `stepSize` is (calculated to be) 2830294800, which in hex is 0xA8B2DF10, which interpreted as a *signed* 32-bit integer, is -1464672496. Which is what the time is actually changing by on each step in your example.

It'd be nice if that were documented somewhere.

I can look into some possible fixes. For now, with the dataset you have on that site, you should be able to set `steps: 2000` in the options. This could slow things down somewhat, depending on your system (set it to 10000 to see an extreme case), but for me 2000 seemed fine.

**Comment by PennyBeames** [comment]
Hey!

Thanks for replying so quick. Your response has definitely expose my newbie-ness! Folks like you write the magic, hacks like me cram the magic into projects. :)

I've set the step size to 2000 and it works like a charm now.

**Comment by skeate** [comment]
Oh hey! I forgot this was something @vencax fixed in one of his PRs, with c275f85971b3fa6b82bca14ab993840b3990a9ce. Merging that stuff in now

Thanks again for reporting the issue!
