### ISSUE TITLE
Leaflet.timeline in a website using webpack

### ISSUE THREAD

**Issue by felixfkrull** [skeate/Leaflet.timeline#68]
Hi,
I wonder wether it's possible to use leaflet.timeline in my website project by installing it with webpack?
I tried
`npm install --save leaflet.timeline`
and some files got copied into the node_modules sub directory.
But importing leaflet.timeline into my website's js file using
`import ltl from 'leaflet.timeline';`
leads to an
`Module not found: Error: Can't resolve 'leaflet.timeline' in ...`
message when I try to build it with webpack.
What am I doing wrong?
Or isn't it possible this way?
Do I have to build the leaflet.timeline.js by my self and copy it manually into my website and require it using <script>-tags?

**Comment by skeate** [comment]
Looks like the published package is missing any actual code file. Whoops.

I've just published 1.0.1 which actually includes a source file.

That said, it's still written in a non-modular way. I _think_ it will still work, but you should just `import 'leaflet.timeline';` and then use `L.Timeline` and `L.TimelineSliderControl` (which are defined on the global `L` object that Leaflet exports)

**Comment by felixfkrull** [comment]
Works now!
Thanks!
Can be closed.
