### ISSUE TITLE
some of the sources not available

### ISSUE THREAD

**Issue by baizuranapiah** [skeate/Leaflet.timeline#70]
in the earthqukes.html file, leaflet-src.js, leaflet.timeline.js and leaflet.css could not be found within the downloaded folder.

I replaced leaflet-src.js with  
<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
   integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
   crossorigin=""></script>

and

leaflet.css with
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
   integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
   crossorigin=""/>

it worked.

but i need clarification if leaflet.timeline.js is the same as Timeline.js in src folder?

and what abput TimelineSliderControl.js? when do we use it?

really hope for an answer. thanks

**Comment by skeate** [comment]
The example is meant to work when you pull the repository and run `npm start`. The `leaflet.timeline.js` file is just the output of the build (which combines all the files in the src folder).

Please install the package via npm with `npm install --save leaflet.timeline`.

**Comment by baizuranapiah** [comment]
thank you very much. now the codes working!
